# Generated by Django 5.0.2 on 2024-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Haber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="Haber Fotoğrafları")),
                ("url", models.CharField(max_length=250)),
                ("date", models.DateTimeField()),
                ("source", models.CharField(max_length=150)),
            ],
        ),
    ]
