# Generated by Django 5.0.2 on 2024-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppHaber", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="source",
            field=models.CharField(max_length=250),
        ),
    ]
