# Generated by Django 5.0.2 on 2024-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppHaber", "0002_alter_haber_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
