# Generated by Django 5.0.2 on 2024-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppHaber", "0003_alter_haber_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
    ]
