# Generated by Django 5.0.2 on 2024-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppHaber", "0004_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaberSites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="Haber",
        ),
    ]
