# Generated by Django 5.0.2 on 2024-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppHaber", "0005_habersites_delete_haber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habersites",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Haber Sitesi Adı"),
        ),
    ]
